// <auto-generated />
using System;
using Lvq_Day09Lab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LVQ_Day09Lab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017071008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_ChiTietHoaDon", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<decimal>("Lvq_DonGiaMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Lvq_HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("Lvq_SanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("Lvq_SoLuongMua")
                        .HasColumnType("int");

                    b.Property<decimal>("Lvq_ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.HasIndex("Lvq_HoaDonID");

                    b.HasIndex("Lvq_SanPhamID");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_HoaDon", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<string>("Lvq_DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_HoTenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lvq_KhachHangID")
                        .HasColumnType("int");

                    b.Property<string>("Lvq_MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lvq_NgayHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Lvq_NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Lvq_TongTriGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.HasIndex("Lvq_KhachHangID");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_KhachHang", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<string>("Lvq_DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_HoTenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lvq_NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_LoaiSanPham", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<string>("Lvq_MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_QuanTri", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<string>("Lvq_MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvq_TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.ToTable("QuanTris");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_SanPham", b =>
                {
                    b.Property<int>("Lvq_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lvq_ID"));

                    b.Property<decimal>("Lvq_DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lvq_HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lvq_LoaiSanPhamID")
                        .HasColumnType("int");

                    b.Property<string>("Lvq_MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lvq_SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Lvq_TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lvq_TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Lvq_ID");

                    b.HasIndex("Lvq_LoaiSanPhamID");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_ChiTietHoaDon", b =>
                {
                    b.HasOne("LVQ_Day09Lab.Models.Lvq_HoaDon", "Lvq_HoaDon")
                        .WithMany("Lvq_ChiTietHoaDons")
                        .HasForeignKey("Lvq_HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LVQ_Day09Lab.Models.Lvq_SanPham", "Lvq_SanPham")
                        .WithMany("Lvq_ChiTietHoaDons")
                        .HasForeignKey("Lvq_SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lvq_HoaDon");

                    b.Navigation("Lvq_SanPham");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_HoaDon", b =>
                {
                    b.HasOne("LVQ_Day09Lab.Models.Lvq_KhachHang", "Lvq_KhachHang")
                        .WithMany("Lvq_HoaDons")
                        .HasForeignKey("Lvq_KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lvq_KhachHang");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_SanPham", b =>
                {
                    b.HasOne("LVQ_Day09Lab.Models.Lvq_LoaiSanPham", "Lvq_LoaiSanPham")
                        .WithMany("Lvq_SanPhams")
                        .HasForeignKey("Lvq_LoaiSanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lvq_LoaiSanPham");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_HoaDon", b =>
                {
                    b.Navigation("Lvq_ChiTietHoaDons");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_KhachHang", b =>
                {
                    b.Navigation("Lvq_HoaDons");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_LoaiSanPham", b =>
                {
                    b.Navigation("Lvq_SanPhams");
                });

            modelBuilder.Entity("LVQ_Day09Lab.Models.Lvq_SanPham", b =>
                {
                    b.Navigation("Lvq_ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
